language: python

cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
- pypy
- pypy3
- 2.7
- 3.6
- 3.5
- 3.4

# Container-based infrastructure
sudo: false

install: pip install -e .

script: clonedigger .

after_script:
 # Static analysis
 - pip install -U pycodestyle pyflakes
 - pyflakes .
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
  allow_failures:
    - python: pypy
    - python: pypy3
    - python: 3.6
    - python: 3.5
    - python: 3.4
